llm_url: "https://api.perplexity.ai"
llm_model: "sonar-pro"
remove_perplexity_citations: true
code_syntax_theme: "dracula"
system_content: |  #Markdown respnses are important as this gots converted in ANSI, Icons, and Emojis
  You are an artificial intelligence assistant and you will
  engage in a helpful, detailed, conversation with a user while
  using markdown for formatting
bullet_point_unicode: "\U0001F680" #Rocket Emoji ğŸš€. Use format \U0001F680 required for Python
header_1: [bold, red, underline ]
header_2: [bold, green, underline ]
header_3: [bold, blue , underline]
ascii_divider_position: center # left , center , right
ascii_divider_choice: 37  # Choose 'ascii_dividers' number or "random" for new divider randomly 
ascii_dividers:
  2: "â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€ â‹†â‹…â˜†â‹…â‹† â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€"
  5: "â†â†â†â† â† â† â† â†â†â†â† â† â† â†â†â†â† â† â† â† â†â†â†â† â† â† â†â†â†â† â† â† â† â†â†â†â† â† â† â†â†â†â† â† â† â† â†â†â†â† â† â† â†â†â†â† â† â† â† â†â†â†â† â† â† "
  7: "â•­â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â•¯â—ˆâ•°â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â•®"
  9: "â–‘â–’â–“â–ˆâ–“â–’â–’â–’â–’â–‘â–‘â–’â–’â–‘â–‘â–’â–’â–‘â–‘â–’â–’â–‘â–‘â–’â–’â–‘â–‘â–’â–’â–‘â–‘â–’â–’â–’â–’â–“â–ˆâ–“â–’â–‘"
  15: "â‰‹â‰‹â‰‹â‰‹â‰‹â‰‹â‰‹â‰‹â‰‹â‰‹â‰‹â‰‹â‰‹â‰‹â‰‹â‰‹â‰‹â‰‹â‰‹â‰‹â‰‹â‰‹â‰‹â‰‹â‰‹â‰‹â‰‹â‰‹â‰‹â‰‹â‰‹â‰‹â‰‹â‰‹â‰‹â‰‹â‰‹â‰‹â‰‹â‰‹â‰‹â‰‹â‰‹â‰‹â‰‹â‰‹â‰‹â‰‹â‰‹â‰‹â‰‹â‰‹â‰‹â‰‹"
  16: "â–‘â–‘â–’â–’â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–’â–’â–‘â–‘"
  18: " â‹†â‹…â˜†â‹…â‹† â”€â”€â”€â”€â”€â”€â”€â”€  â‹†â‹…â˜†â‹…â‹† â”€â”€â”€â”€â”€â”€â”€â”€  â‹†â‹…â˜†â‹…â‹† â”€â”€â”€â”€â”€â”€â”€â”€  â‹†â‹…â˜†â‹…â‹† â”€â”€â”€â”€â”€â”€â”€â”€  â‹†â‹…â˜†â‹…â‹† ""
  23: "â˜¾â‹†â˜½â˜¾â‹†â˜½â˜¾â‹†â˜½â˜¾â‹†â˜½â˜¾â‹†â˜½â˜¾â‹†â˜½â˜¾â‹†â˜½â˜¾â‹†â˜½â˜¾â‹†â˜½â˜¾â‹†â˜½â˜¾â‹†â˜½â˜¾â‹†â˜½â˜¾â‹†â˜½â˜¾â‹†â˜½â˜¾â‹†â˜½â˜¾â‹†â˜½â˜¾â‹†â˜½â˜¾â‹†â˜½â˜¾â‹†â˜½â˜¾â‹†â˜½â˜¾â‹†â˜½â˜¾â‹†â˜½"
  24: "â•­â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€-â€¢Â¯\_(ãƒ„)_/Â¯â€¢-â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â•®"
  25: "âœ©Ëšï½¡â‹†ï½¡Ëšï½¡â‹†ï½¡Ëšï½¡â‹†ï½¡Ëšï½¡â‹†ï½¡Ëšï½¡â‹†ï½¡Ëšï½¡â‹†ï½¡Ëšï½¡â‹†ï½¡Ëšï½¡â‹†ï½¡Ëšï½¡â‹†ï½¡Ëšï½¡â‹†ï½¡Ëšï½¡â‹†ï½¡Ëšï½¡â‹†ï½¡Ëšï½¡â‹†ï½¡Ëšï½¡â‹†ï½¡Ëšâœ©"
  26: "-Â·=Â»â—†Â«=Â·-Â·=Â»â—†Â«=Â·-Â·=Â»â—†Â«=Â·-Â·=Â»â—†Â«=Â·-Â·=Â»â—†Â«=Â·-Â·=Â»â—†Â«=Â·-Â·=Â»â—†Â«=Â·-Â·=Â»â—†Â«=Â·-"
  27: "*â€¢.Â¸â›§Â¸.â€¢*â€¢.Â¸â›§Â¸.â€¢*â€¢.Â¸â›§Â¸.â€¢*â€¢.Â¸â›§Â¸.â€¢*â€¢.Â¸â›§Â¸.â€¢*â€¢.Â¸â›§Â¸.â€¢*â€¢.Â¸â›§Â¸.â€¢*â€¢.Â¸â›§Â¸.â€¢*"
  27: "Â¸.â€¢*Â¯\_(ãƒ„)_/Â¯*â€¢.Â¸âŠ¹Â¸.â€¢*â€¢.Â¸âŠ¹Â¸.â€¢*Â¯\_(ãƒ„)_/Â¯*â€¢.Â¸âŠ¹Â¸.â€¢*â€¢.Â¸âŠ¹Â¸.â€¢*Â¯\_(ãƒ„)_/Â¯*â€¢.Â¸"
  31: "- = â˜† = - = â˜† = - = â˜† = - = â˜† = - = â˜† =  - = â˜† = - = â˜† = - = â˜† = -"
  32: "Â¯\_(ãƒ„)_/Â¯Â¯\_(ãƒ„)_/Â¯Â¯\_(ãƒ„)_/Â¯Â¯\_(ãƒ„)_/Â¯Â¯\_(ãƒ„)_/Â¯Â¯\_(ãƒ„)_/Â¯"
  34: "=^..^=   =^..^=   =^..^=    =^..^=    =^..^=    =^..^=    =^..^="
  35: ".oOo.oOo.oOo.oOo.oOo.oOo.oOo.oOo.oOo.oOo.oOo.oOo.oOo.oOo.oOo."
  36: "â€§Ëšâ‚Šê’·ê’¦ï¸¶ï¸¶ï¸¶ï¸¶ï¸¶ê’·ê’¦ï¸¶ï¸¶ï¸¶ï¸¶ï¸¶ê’¦ï¸¶ï¸¶ï¸¶ï¸¶ï¸¶ê’·ê’¦ï¸¶ï¸¶ï¸¶ï¸¶ï¸¶ê’¦ê’·â€§â‚ŠËšâŠ¹"
  37: "âŠ¹Ëšâ‚Šâ€§â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â€§â‚ŠËšâŠ¹"
  38: "â›§ Â· Â· â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€ Â·â˜½â—¯â˜¾Â· â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€ Â· Â· â›§"
  39: "â›§ â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€ â‹†â‹…â˜†â‹…â‹† â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€ â›§"
  40: "â€¢â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â‹…â˜¾ â˜½â‹…â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â€¢"
  42: "â­’ â˜† â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â” â˜† â­’ â­’ â˜† â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â” â˜† â­’"
  43: "â€§Ëšâ‚Šê’·ê’¦ï¸¶ï¸¶ï¸¶ï¸¶ï¸¶ï¸¶ï¸¶ï¸¶ï¸¶ Â¯\_(ãƒ„)_/Â¯ ï¸¶ï¸¶ï¸¶ï¸¶ï¸¶ï¸¶ï¸¶ï¸¶ï¸¶ï¸¶ï¸¶ê’¦ê’·â€§â‚ŠËšâŠ¹"
  45: "--------------------------------------------------"
  46: "Â°ÂºÂ¤Ã¸,Â¸Â¸,Ã¸Â¤ÂºÂ°`Â°ÂºÂ¤Ã¸,Â¸,Ã¸Â¤Â°ÂºÂ¤Ã¸,Â¸Â¸,Ã¸Â¤ÂºÂ°`Â°ÂºÂ¤Ã¸,Â¸Â°ÂºÂ¤Ã¸,Â¸Â¸,Ã¸Â¤ÂºÂ°`Â°ÂºÂ¤Ã¸,Â¸,Ã¸Â¤Â°Âº"
  48: " (ã£â—•â€¿â—•)ã£ (ã£â—•â€¿â—•)ã£ (ã£â—•â€¿â—•)ã£ (ã£â—•â€¿â—•)ã£ (ã£â—•â€¿â—•)ã£ (ã£â—•â€¿â—•)ã£ (ã£â—•â€¿â—•)ã£"
  50: "Â°Â´Â¯`Â·.Â¸.Â·Â´Â¯`Â°Â´Â¯`Â·.Â¸.Â·Â´Â¯`Â°Â´Â¯`Â·.Â¸.Â·Â´Â¯`Â°Â´Â¯`Â·.Â¸.Â·Â´Â¯`Â°Â´Â¯`Â·.Â¸.Â·Â´Â¯`Â°"
  51: "Â»Â»---â–º Â»Â»---â–º Â»Â»---â–º Â»Â»---â–º Â»Â»---â–º Â»Â»---â–º Â»Â»---â–º Â»Â»---â–º Â»Â»---â–º Â»Â»---â–º "
  52: " ( Í¡Â° ÍœÊ– Í¡Â°) ( Í¡Â° ÍœÊ– Í¡Â°) ( Í¡Â° ÍœÊ– Í¡Â°) ( Í¡Â° ÍœÊ– Í¡Â°) ( Í¡Â° ÍœÊ– Í¡Â°) ( Í¡Â° ÍœÊ– Í¡Â°) ( Í¡Â° ÍœÊ– Í¡Â°) ( Í¡Â° ÍœÊ– Í¡Â°)"
  54: ""
