llm_url: "https://api.perplexity.ai"
llm_model: "sonar-pro"
remove_perplexity_citations: true
code_syntax_theme: "dracula"
system_content: |  #Markdown respnses are important as this gots converted in ANSI, Icons, and Emojis
  You are an AI assistant for terminal used by software engineers, SRE,  and technical startup founders.
  FORMAT: Use standard markdown (##, -, *, ```, [link](https://link.com)) for output. Do not use horizontal dividers to separate code and text. 
  STYLE: Be concise, accurate, and direct. Assume technical competence. Provide actionable solutions with examples. Use appropriate technical terminology and highlight best practices. Start and end each request with a markdown '---'. 
  When referring to a URL include the full URL inline.  
bullet_point_unicode: "\U0001F680" #Rocket Emoji ğŸš€. Use format \U0001F680 required for Python.use " in yaml for unicode.
header_1: [bold, magenta, underline ]
header_2: [bold, green, underline ]
header_3: [bold, cyan , underline]
header_4: [bold, yellow, underline ]
header_5: [bold, blue, underline ]
header_6: [bold, red , underline]
ascii_divider_position: center # left , center , right
ascii_divider_choice: 46  # Choose 'ascii_dividers' number or "random" for new divider randomly 
ascii_dividers: #Single qoutes to avoid issues with escaping \
  2: 'â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€ â‹†â‹…â˜†â‹…â‹† â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€'
  5: 'â†â†â†â† â† â† â† â†â†â†â† â† â† â†â†â†â† â† â† â† â†â†â†â† â† â† â†â†â†â† â† â† â† â†â†â†â† â† â† â†â†â†â† â† â† â† â†â†â†â† â† â† â†â†â†â† â† â† â† â†â†â†â† â† â† '
  7: 'â•­â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â•¯â—ˆâ•°â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â•®'
  9: 'â–‘â–‘â–‘â–’â–’â–’â–’â–“â–“â–“â–“â–“â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–“â–“â–“â–“â–“â–“â–’â–’â–’â–’â–‘â–‘â–‘'
  15: 'â‰‹â‰‹â‰‹â‰‹â‰‹â‰‹â‰‹â‰‹â‰‹â‰‹â‰‹â‰‹â‰‹â‰‹â‰‹â‰‹â‰‹â‰‹â‰‹â‰‹â‰‹â‰‹â‰‹â‰‹â‰‹â‰‹â‰‹â‰‹â‰‹â‰‹â‰‹â‰‹â‰‹â‰‹â‰‹â‰‹â‰‹â‰‹â‰‹â‰‹â‰‹â‰‹â‰‹â‰‹â‰‹â‰‹â‰‹â‰‹â‰‹â‰‹â‰‹â‰‹â‰‹â‰‹'
  16: 'â–‘â–‘â–’â–’â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–’â–’â–‘â–‘'
  17: 'Â»Â»â€”â€”âŸâ€”â€”Â«Â«Â»Â»â€”â€”âŸâ€”â€”Â«Â«Â»Â»â€”â€”âŸâ€”â€”Â«Â«Â»Â»â€”â€”âŸâ€”â€”Â«Â«Â»Â»â€”â€”âŸâ€”â€”Â«Â«Â»Â»â€”â€”âŸâ€”â€”Â«Â«Â»Â»â€”â€”âŸâ€”â€”Â«Â«Â»Â»â€”â€”âŸâ€”â€”Â«Â«'
  18: ' â‹†â‹…â˜†â‹…â‹† â”€â”€â”€â”€â”€â”€â”€â”€  â‹†â‹…â˜†â‹…â‹† â”€â”€â”€â”€â”€â”€â”€â”€  â‹†â‹…â˜†â‹…â‹† â”€â”€â”€â”€â”€â”€â”€â”€  â‹†â‹…â˜†â‹…â‹† â”€â”€â”€â”€â”€â”€â”€â”€  â‹†â‹…â˜†â‹…â‹† '
  23: 'â˜¾â‹†â˜½â˜¾â‹†â˜½â˜¾â‹†â˜½â˜¾â‹†â˜½â˜¾â‹†â˜½â˜¾â‹†â˜½â˜¾â‹†â˜½â˜¾â‹†â˜½â˜¾â‹†â˜½â˜¾â‹†â˜½â˜¾â‹†â˜½â˜¾â‹†â˜½â˜¾â‹†â˜½â˜¾â‹†â˜½â˜¾â‹†â˜½â˜¾â‹†â˜½â˜¾â‹†â˜½â˜¾â‹†â˜½â˜¾â‹†â˜½â˜¾â‹†â˜½â˜¾â‹†â˜½â˜¾â‹†â˜½'
  24: 'â•­â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€-â€¢Â¯\_(ãƒ„)_/Â¯â€¢-â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â•®'
  25: 'âœ©Ëšï½¡â‹†ï½¡Ëšï½¡â‹†ï½¡Ëšï½¡â‹†ï½¡Ëšï½¡â‹†ï½¡Ëšï½¡â‹†ï½¡Ëšï½¡â‹†ï½¡Ëšï½¡â‹†ï½¡Ëšï½¡â‹†ï½¡Ëšï½¡â‹†ï½¡Ëšï½¡â‹†ï½¡Ëšï½¡â‹†ï½¡Ëšï½¡â‹†ï½¡Ëšï½¡â‹†ï½¡Ëšï½¡â‹†ï½¡Ëšâœ©'
  26: '-Â·=Â»â—†Â«=Â·-Â·=Â»â—†Â«=Â·-Â·=Â»â—†Â«=Â·-Â·=Â»â—†Â«=Â·-Â·=Â»â—†Â«=Â·-Â·=Â»â—†Â«=Â·-Â·=Â»â—†Â«=Â·-Â·=Â»â—†Â«=Â·-'
  27: '*â€¢.Â¸â›§Â¸.â€¢*â€¢.Â¸â›§Â¸.â€¢*â€¢.Â¸â›§Â¸.â€¢*â€¢.Â¸â›§Â¸.â€¢*â€¢.Â¸â›§Â¸.â€¢*â€¢.Â¸â›§Â¸.â€¢*â€¢.Â¸â›§Â¸.â€¢*â€¢.Â¸â›§Â¸.â€¢*'
  27: 'Â¸.â€¢*Â¯\_(ãƒ„)_/Â¯*â€¢.Â¸âŠ¹Â¸.â€¢*â€¢.Â¸âŠ¹Â¸.â€¢*Â¯\_(ãƒ„)_/Â¯*â€¢.Â¸âŠ¹Â¸.â€¢*â€¢.Â¸âŠ¹Â¸.â€¢*Â¯\_(ãƒ„)_/Â¯*â€¢.Â¸'
  31: '- = â˜† = - = â˜† = - = â˜† = - = â˜† = - = â˜† =  - = â˜† = - = â˜† = - = â˜† = -'
  32: 'Â¯\_(ãƒ„)_/Â¯Â¯\_(ãƒ„)_/Â¯Â¯\_(ãƒ„)_/Â¯Â¯\_(ãƒ„)_/Â¯Â¯\_(ãƒ„)_/Â¯Â¯\_(ãƒ„)_/Â¯'
  34: '=^..^=   =^..^=   =^..^=    =^..^=    =^..^=    =^..^=    =^..^='
  35: '.oOo.oOo.oOo.oOo.oOo.oOo.oOo.oOo.oOo.oOo.oOo.oOo.oOo.oOo.oOo.'
  36: 'â€§Ëšâ‚Šê’·ê’¦ï¸¶ï¸¶ï¸¶ï¸¶ï¸¶ê’·ê’¦ï¸¶ï¸¶ï¸¶ï¸¶ï¸¶ê’¦ï¸¶ï¸¶ï¸¶ï¸¶ï¸¶ê’·ê’¦ï¸¶ï¸¶ï¸¶ï¸¶ï¸¶ê’¦ê’·â€§â‚ŠËšâŠ¹'
  37: 'âŠ¹Ëšâ‚Šâ€§â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â€§â‚ŠËšâŠ¹'
  38: 'â›§ Â· Â· â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€ Â·â˜½â—¯â˜¾Â· â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€ Â· Â· â›§'
  39: 'â›§ â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€ â‹†â‹…â˜†â‹…â‹† â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€ â›§'
  40: 'â€¢â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â‹…â˜¾ â˜½â‹…â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â€¢'
  42: 'â­’ â˜† â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â” â˜† â­’ â­’ â˜† â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â” â˜† â­’'
  43: 'â€§Ëšâ‚Šê’·ê’¦ï¸¶ï¸¶ï¸¶ï¸¶ï¸¶ï¸¶ï¸¶ï¸¶ï¸¶ Â¯\_(ãƒ„)_/Â¯ ï¸¶ï¸¶ï¸¶ï¸¶ï¸¶ï¸¶ï¸¶ï¸¶ï¸¶ï¸¶ï¸¶ê’¦ê’·â€§â‚ŠËšâŠ¹'
  45: '--------------------------------------------------'
  46: 'Â°ÂºÂ¤Ã¸,Â¸Â¸,Ã¸Â¤ÂºÂ°`Â°ÂºÂ¤Ã¸,Â¸,Ã¸Â¤Â°ÂºÂ¤Ã¸,Â¸Â¸,Ã¸Â¤ÂºÂ°`Â°ÂºÂ¤Ã¸,Â¸Â°ÂºÂ¤Ã¸,Â¸Â¸,Ã¸Â¤ÂºÂ°'
  48: ' (ã£â—•â€¿â—•)ã£ (ã£â—•â€¿â—•)ã£ (ã£â—•â€¿â—•)ã£ (ã£â—•â€¿â—•)ã£ (ã£â—•â€¿â—•)ã£ (ã£â—•â€¿â—•)ã£ (ã£â—•â€¿â—•)ã£'
  50: 'Â°Â´Â¯`Â·.Â¸.Â·Â´Â¯`Â°Â´Â¯`Â·.Â¸.Â·Â´Â¯`Â°Â´Â¯`Â·.Â¸.Â·Â´Â¯`Â°Â´Â¯`Â·.Â¸.Â·Â´Â¯`Â°Â´Â¯`Â·.Â¸.Â·Â´Â¯`Â°'
  51: 'Â»Â»---â–º Â»Â»---â–º Â»Â»---â–º Â»Â»---â–º Â»Â»---â–º Â»Â»---â–º Â»Â»---â–º Â»Â»---â–º Â»Â»---â–º Â»Â»---â–º '
  52: ' ( Í¡Â° ÍœÊ– Í¡Â°) ( Í¡Â° ÍœÊ– Í¡Â°) ( Í¡Â° ÍœÊ– Í¡Â°) ( Í¡Â° ÍœÊ– Í¡Â°) ( Í¡Â° ÍœÊ– Í¡Â°) ( Í¡Â° ÍœÊ– Í¡Â°) ( Í¡Â° ÍœÊ– Í¡Â°) ( Í¡Â° ÍœÊ– Í¡Â°)'
code_divider_choice: 5  # choice , no random
code_dividers:
  1: 'â–‘â–‘â–’â–’â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–’â–’â–‘â–‘'
  2: 'â–‘â–‘â–‘â–’â–’â–’â–’â–“â–“â–“â–“â–“â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–“â–“â–“â–“â–“â–“â–’â–’â–’â–’â–‘â–‘â–‘'
  3: 'â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â•¯ ğŸ› ï¸ â•°â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€'
  4: ' (ã£â—•â€¿â—•)ã£ cODE (ã£â—•â€¿â—•)ã£ bLOCK (ã£â—•â€¿â—•)ã£ cODE (ã£â—•â€¿â—•)ã£ bLOCK (ã£â—•â€¿â—•)ã£'
  5: 'âŠ¹Ëšâ‚Šâ€§â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€-â€¢ cODE Â¯\_(ãƒ„)_/Â¯ bLOCK â€¢-â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â€§â‚ŠËšâŠ¹'
