header_1: [bold, green, underline ]
header_2: [bold, blue ]
header_3: [bold, red ]
bullet_point_emoji: "\U0001F680" #Rocket Emoji ğŸš€. Use format \U0001F680 required for Python
# ANSI Divider: Markdown divider "---" is removed and replaced with ANSI dividers below. Add a 
# New divider to ansi_dividers and select it with ansi_divider_choice to enable it in the code
ansi_divider_position: center # left , center , right
ansi_divider_choice: 16 # Choose or create divider below
ansi_dividers:
  1: "âœ§à¼ºâœ¦âœ®âœ¦à¼»âˆ âˆà¼ºâœ¦âœ®âœ¦à¼»âœ§"
  2: "â”€â”€â”€â”€ â‹†â‹…â˜†â‹…â‹† â”€â”€â”€â”€"
  3: "â–â•â•â•â•â•â•â–â•â•â•â•â•â•â–"
  4: "â•­â”â”â”â•®â•°â”â”â”â•¯â•­â”â”â”â•®"
  5: "â†â†â†â† â† â† â† â†â†â†â† â† â† "
  6: "â•°â˜†â˜†â˜†â•®â˜†â˜†â˜†â•°â˜†â˜†â˜†â•®"
  7: "â•­â”€â”€â”€â”€â”€â”€â•¯â—ˆâ•°â”€â”€â”€â”€â”€â”€â•®"
  8: "âœ¿â€ââ€âœ¿â€ââ€âœ¿"
  9: "â–‘â–’â–“â–ˆâ–“â–’â–‘â–’â–“â–ˆâ–“â–’â–‘"
  10: "â•­â•â˜†â•â•¯â•â˜†â•â•­â•â˜†â•â•¯"
  11: "â”€â”â”€â—â”€â”â”€â—â”€â”â”€â—â”€â”â”€"
  12: "â—ˆâ”€â”€â”€â”€â”€â”€â—ˆâ”€â”€â”€â”€â”€â”€â—ˆ"
  13: "â•°âŠ±â‹…â‹…âŠ°â•¯âŠ±â‹…â‹…âŠ°â•¯âŠ±â‹…â‹…âŠ°â•¯"
  14: "â˜…å½¡â˜…å½¡â˜…å½¡â˜…å½¡â˜…å½¡â˜…å½¡"
  15: "â‰‹â‰‹â‰‹â‰‹â‰‹â‰‹â‰‹â‰‹â‰‹â‰‹â‰‹â‰‹â‰‹â‰‹â‰‹"
  16: "â–‘â–‘â–’â–’â–“â–“â–’â–’â–‘â–‘â–’â–’â–“â–“â–’â–’â–‘â–‘"
  17: "âœ§ï½¥ï¾Ÿ: *âœ§ï½¥ï¾Ÿ:* *:ï½¥ï¾Ÿâœ§*:ï½¥ï¾Ÿâœ§"
  18: "â™¡â”€â”€â”€â”€â”€â”€â”€â”€â™¡â”€â”€â”€â”€â”€â”€â”€â”€â™¡"
  19: "â–„â–„â–„â–„â–„â–„â–„â–„â–„â–„â–„â–„â–„â–„â–„â–„â–„â–„â–„â–„"
  20: "â•”â•â•â•—â•‘â•â•â•â•â•‘â•‘â•â•â•â•â•‘â•”â•â•â•—"
  21: "âœ¦âœ§âœ¦âœ§âœ¦âœ§âœ¦âœ§âœ¦âœ§âœ¦âœ§âœ¦âœ§"
  22: "â—¤â”â”â”â”â”â”â”â—¥â”â”â”â”â”â”â”â—¤"
  23: "â˜¾â‹†â˜½â˜¾â‹†â˜½â˜¾â‹†â˜½â˜¾â‹†â˜½"
  24: "â•­â”€â”€â”€â”€â”€-â—ˆ-â”€â”€â”€â”€â”€â•®"
  25: "âœ©Ëšï½¡â‹†ï½¡Ëšï½¡â‹†ï½¡Ëšï½¡â‹†ï½¡Ëšï½¡â‹†ï½¡Ëšï½¡â‹†ï½¡Ëš"
  26: "-Â·=Â»â—†Â«=Â·-Â·=Â»â—†Â«=Â·-Â·=Â»â—†Â«=Â·-"
  27: "*â€¢.Â¸â™¡Â¸.â€¢*â€¢.Â¸â™¡Â¸.â€¢*â€¢.Â¸â™¡Â¸.â€¢*"
  28: "=â‰¡â˜†â‰¡=â‰¡â˜†â‰¡=â‰¡â˜†â‰¡=â‰¡â˜†â‰¡=â‰¡â˜†â‰¡="
  29: "~â€¢~â€¢~â€¢~â€¢~â€¢~â€¢~â€¢~â€¢~â€¢~â€¢~â€¢~â€¢~â€¢~â€¢~â€¢~"
  30: "<><><><><><><><><><>"
  31: "-=â˜†=-=â˜†=-=â˜†=-=â˜†=-=â˜†=-=â˜†=-=â˜†=-=â˜†=-=â˜†"
# Pygment Python Library syntax styles setting. Mark code block will be colored with this theme
# Check what these would look like by using the Pygment style checker. Check which syntax type
# "Python" , etc and use the dropdown to check themes. https://pygments.org/demo/. If extra styles
# are added just add them below in a new numbered line and set code_syntax_choice to style number.
code_syntax_choice: 31
code_syntax_themes:
  1: "abap"
  2: "algol"
  3: "algol_nu"
  4: "arduino"
  5: "autumn"
  6: "bw"
  7: "borland"
  8: "coffee"
  9: "colorful"
  10: "default"
  11: "dracula"
  12: "emacs"
  13: "friendly_grayscale"
  14: "friendly"
  15: "fruity"
  16: "github-dark"
  17: "gruvbox-dark"
  18: "gruvbox-light"
  19: "igor"
  20: "inkpot"
  21: "lightbulb"
  22: "lilypond"
  23: "lovelace"
  24: "manni"
  25: "material"
  26: "monokai"
  27: "murphy"
  28: "native"
  29: "nord-darker"
  30: "nord"
  31: "one-dark"
  32: "paraiso-dark"
  33: "paraiso-light"
  34: "pastie"
  35: "perldoc"
  36: "rainbow_dash"
  37: "rrt"
  38: "sas"
  39: "solarized-dark"
  40: "solarized-light"
  41: "staroffice"
  42: "stata-dark"
  43: "stata-light"
  44: "tango"
  45: "trac"
  46: "vim"
  47: "vs"
  48: "xcode"
  49: "zenburn"

