llm_url: "https://api.perplexity.ai"
llm_model: "sonar-pro"
stream_output: true 
code_syntax_theme: "one-dark"
system_content: |  #Markdown respnses are important as this gots converted in ANSI, Icons, and Emojis
  You are an artificial intelligence assistant and you will
  engage in a helpful, detailed, conversation with a user while
  using markdown for formatting
bullet_point_unicode: "\U0001F680" #Rocket Emoji ğŸš€. Use format \U0001F680 required for Python
header_1: [bold, red, underline ]
header_2: [bold, green, underline ]
header_3: [bold, blue , underline]
ansi_divider_position: center # left , center , right
ansi_divider_choice: 16 # Choose number or "random"
ansi_dividers:
  1: "âœ§à¼ºâœ¦âœ®âœ¦à¼»âˆ âˆà¼ºâœ¦âœ®âœ¦à¼»âœ§"
  2: "â”€â”€â”€â”€ â‹†â‹…â˜†â‹…â‹† â”€â”€â”€â”€"
  3: "â–â•â•â•â•â•â•â–â•â•â•â•â•â•â–"
  4: "â•­â”â”â”â•®â•°â”â”â”â•¯â•­â”â”â”â•®"
  5: "â†â†â†â† â† â† â† â†â†â†â† â† â† "
  6: "â•°â˜†â˜†â˜†â•®â˜†â˜†â˜†â•°â˜†â˜†â˜†â•®"
  7: "â•­â”€â”€â”€â”€â”€â”€â•¯â—ˆâ•°â”€â”€â”€â”€â”€â”€â•®"
  8: "âœ¿â€ââ€âœ¿â€ââ€âœ¿"
  9: "â–‘â–’â–“â–ˆâ–“â–’â–‘â–’â–“â–ˆâ–“â–’â–‘"
  10: "â•­â•â˜†â•â•¯â•â˜†â•â•­â•â˜†â•â•¯"
  11: "â”€â”â”€â—â”€â”â”€â—â”€â”â”€â—â”€â”â”€"
  12: "â—ˆâ”€â”€â”€â”€â”€â”€â—ˆâ”€â”€â”€â”€â”€â”€â—ˆ"
  13: "â•°âŠ±â‹…â‹…âŠ°â•¯âŠ±â‹…â‹…âŠ°â•¯âŠ±â‹…â‹…âŠ°â•¯"
  14: "â˜…å½¡â˜…å½¡â˜…å½¡â˜…å½¡â˜…å½¡â˜…å½¡"
  15: "â‰‹â‰‹â‰‹â‰‹â‰‹â‰‹â‰‹â‰‹â‰‹â‰‹â‰‹â‰‹â‰‹â‰‹â‰‹"
  16: "â–‘â–‘â–’â–’â–“â–“â–’â–’â–‘â–‘â–’â–’â–“â–“â–’â–’â–‘â–‘"
  17: "âœ§ï½¥ï¾Ÿ: *âœ§ï½¥ï¾Ÿ:* *:ï½¥ï¾Ÿâœ§*:ï½¥ï¾Ÿâœ§"
  18: "â™¡â”€â”€â”€â”€â”€â”€â”€â”€â™¡â”€â”€â”€â”€â”€â”€â”€â”€â™¡"
  19: "â–„â–„â–„â–„â–„â–„â–„â–„â–„â–„â–„â–„â–„â–„â–„â–„â–„â–„â–„â–„"
  20: "â•”â•â•â•—â•‘â•â•â•â•â•‘â•‘â•â•â•â•â•‘â•”â•â•â•—"
  21: "âœ¦âœ§âœ¦âœ§âœ¦âœ§âœ¦âœ§âœ¦âœ§âœ¦âœ§âœ¦âœ§"
  22: "â—¤â”â”â”â”â”â”â”â—¥â”â”â”â”â”â”â”â—¤"
  23: "â˜¾â‹†â˜½â˜¾â‹†â˜½â˜¾â‹†â˜½â˜¾â‹†â˜½"
  24: "â•­â”€â”€â”€â”€â”€-â—ˆ-â”€â”€â”€â”€â”€â•®"
  25: "âœ©Ëšï½¡â‹†ï½¡Ëšï½¡â‹†ï½¡Ëšï½¡â‹†ï½¡Ëšï½¡â‹†ï½¡Ëšï½¡â‹†ï½¡Ëš"
  26: "-Â·=Â»â—†Â«=Â·-Â·=Â»â—†Â«=Â·-Â·=Â»â—†Â«=Â·-"
  27: "*â€¢.Â¸â™¡Â¸.â€¢*â€¢.Â¸â™¡Â¸.â€¢*â€¢.Â¸â™¡Â¸.â€¢*"
  28: "=â‰¡â˜†â‰¡=â‰¡â˜†â‰¡=â‰¡â˜†â‰¡=â‰¡â˜†â‰¡=â‰¡â˜†â‰¡="
  29: "~â€¢~â€¢~â€¢~â€¢~â€¢~â€¢~â€¢~â€¢~â€¢~â€¢~â€¢~â€¢~â€¢~â€¢~â€¢~"
  30: "<><><><><><><><><><>"
  31: "-=â˜†=-=â˜†=-=â˜†=-=â˜†=-=â˜†=-=â˜†=-=â˜†=-=â˜†=-=â˜†"
